package com.example.shopper;

import android.content.Intent;
import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.AdapterView;
import android.widget.ListView;

public class MainActivity extends AppCompatActivity {

    // declare an intent
    Intent intent;

    // declare a DBHandler
    DBHandler dbHandler;

    // declare a Shoping List cursor Adapter
    ShoppingLists shoppingListsAdapter;

    // declare a ListView
    ListView shopperListView;

    /**
     * This method initializes the action bar and
     * view of the main activity
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // this code generated by Android Studio initializes the
        // view and Action Bar of the Main Activity
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        // initialize the dbHandler
        dbHandler = new DBHandler(this, null);

        // initialize the ListView
        shopperListView = (ListView) findViewById(R.id.shopperListView);

        // initialize the shopperList cursor adapter
        shoppingListsAdapter = new ShoppingLists(this, dbHandler.getShoppingLists(), 0);

        // set shopping lists cursor adapter
        shopperListView.setAdapter(shoppingListsAdapter);

        // set OnItemClickListener to shopper ListView
        shopperListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long id) {
                // launching the View List Activity and sending it the id of the
                // shopping list
                intent = new Intent(MainActivity.this, ViewList.class);
                intent.putExtra(" _id", id);
                startActivity(intent);
            }
        });
    }

    /**
     * This method further initializes the Action Bar of
     * the Main Activity. It gets tge code we wrote in the
     * menu main and incorporates it into the Action Bar
     * @param menu
     * @return
     */
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    /**
     * This method gets called when an item in the overflow menu is selected and
     * it controls what happens when the item is selected
     * @param item item selected in the overflow menu. It contains information
     *             about the item; for example, its id
     * @return true if item was selected; else returns false
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {

        // get the id of the item that was selected
        switch (item.getItemId()){
            case R.id.action_home :
                intent = new Intent(this, MainActivity.class);
                // initializing an intent for the main activity, starting it
                // and returning true
                startActivity(intent);
                return true;
            case R.id.action_create_list :
                // initializing an intent for the create list activity, starting it
                // and returning true
                intent = new Intent(this, CreateList.class);
                startActivity(intent);
                default:
                    return super.onOptionsItemSelected(item);
        }

    }

    public void openCreateList (View view){
        // initializing an intent for the create list activity and starting it
        intent = new Intent(this, CreateList.class);
        startActivity(intent);
    }
}
